# produtos
GET http://localhost:3000/produtos
_____________________________________________________________________________________________________________________________________
# cliente
_____________________________________________________________________________________________________________________________________
# vendedor
_____________________________________________________________________________________________________________________________________
